### ISSUE TITLE
Path Search 

### ISSUE THREAD

**Issue by brainrichtech** [kevinwang1975/PathFinder#1]
Hi

I am Downloading your code . If i am creating map it successfully created . After creating map if i am going to click path search checkbox window not showing the map.  i got the error Destination not set.

please help me to run the project.  i am waiting for your reply...

thanks
by sakthi
![1](https://cloud.githubusercontent.com/assets/2878390/21073465/f50aba4e-bf04-11e6-93b5-83b96e6804e7.jpg)
![2](https://cloud.githubusercontent.com/assets/2878390/21073470/011599f8-bf05-11e6-879f-ba2a8f65ebf8.jpg)

**Comment by kevinwang1975** [comment]
Hi Sakthi,

On "Map Editing" mode, you need to click on a non-black cell to set
"Destination" for the search (the cell will be painted in red). Then switch
to "Path Search" mode, click on a non-black cell as the start point for the
search. Here is a YouTube link that will give you an idea how to use the
demo app.

https://www.youtube.com/watch?v=g024lzsknDo

Best,
Kevin

**Comment by brainrichtech** [comment]
thank you for your reply...

same way i am doing (youtube video) click non black box after click path search windows going to blank.

https://github.com/kevinwang1975/PathFinder 

use this link try your jar file

thanks
by sakthi

**Comment by brainrichtech** [comment]
![1](https://cloud.githubusercontent.com/assets/2878390/21073617/96889568-bf09-11e6-8d1e-c7acdf3e4d81.jpg)
![2](https://cloud.githubusercontent.com/assets/2878390/21073618/98f2a230-bf09-11e6-9f51-9558412f358a.jpg)
here i am attaching sample output

**Comment by kevinwang1975** [comment]
I just downloaded the JAR file for a quick try, it worked. I ran it as: *java
-jar Downloads/PathFinder.jar*


   1. Clicked on "Generate Map" -> got a random map generated
   2. Clicked on a cell -> the cell painted in red
   3. Click "Path Search" -> switch to the search mode
   4. Clicked on a cell -> the cell painted in green, and search started,
   until hit the destination

Java version: Oracle 1.8.0_111

**Comment by brainrichtech** [comment]
i am using jdk1.8.0_91 32bit
i am directly run the jar file without command prompt.
i got this error.

can you send the code now....

**Comment by kevinwang1975** [comment]
The code is in the GitHub where you found the JAR :-)
You can get a copy by:

git clone https://github.com/kevinwang1975/PathFinder

**Comment by brainrichtech** [comment]
i can run the team viewer can you check it.....

**Comment by kevinwang1975** [comment]
Sorry, can't do that. I don't have that app.
Maybe try to run it from a terminal (java -jar Downloads/PathFinder.jar),
it may show some error messages to help you locate the problem.

**Comment by brainrichtech** [comment]
i got same error if run in terminal.
![1](https://cloud.githubusercontent.com/assets/2878390/21073763/8bd7db7a-bf0d-11e6-9d22-3ca7fc928a8a.jpg)
![2](https://cloud.githubusercontent.com/assets/2878390/21073764/8e44b1f8-bf0d-11e6-9ff3-a600472ab5fb.jpg)
![3](https://cloud.githubusercontent.com/assets/2878390/21073765/91036a6a-bf0d-11e6-96f7-2adc508137fc.jpg)

**Comment by kevinwang1975** [comment]
Seems to have something to do with JDK, unfortunately, I haven't used 32
bit since a long long time ago, don't have the environment to reproduce
that, my suggestion:

   - upgrade JDK to latest (64 bit if possible, it supports larger memory
   space, irrelevant to this case though)
   - run it on another computer
   - download the source code to set some breakpoint to find where it goes
   wrong

**Comment by brainrichtech** [comment]
hi sir,
I am upgrade to JDK 1.8.0_111 -64bit and try to run another computer.
I am got same error.
please help me to run the project
thanking you
by
sakthi

**Comment by kevinwang1975** [comment]
This problem seems to only occur on Windows. It has been fixed. You may
download the JAR and try again.

**Comment by brainrichtech** [comment]
thank you sir
the problem is solved now correctly running
